# Generated by Django 2.0 on 2018-12-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20181219_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Is staf'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
