# Generated by Django 2.0 on 2018-12-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20181227_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is staf'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
